// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.2
// source: enums/enums.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushType int32

const (
	PushType_PUSH_TYPE_UNSPECIFIED  PushType = 0
	PushType_PUSH_TYPE_NOTIFY       PushType = 1
	PushType_PUSH_TYPE_ANNOUNCEMENT PushType = 2
	PushType_PUSH_TYPE_CHAT         PushType = 3
	PushType_PUSH_TYPE_KICK         PushType = 4
)

// Enum value maps for PushType.
var (
	PushType_name = map[int32]string{
		0: "PUSH_TYPE_UNSPECIFIED",
		1: "PUSH_TYPE_NOTIFY",
		2: "PUSH_TYPE_ANNOUNCEMENT",
		3: "PUSH_TYPE_CHAT",
		4: "PUSH_TYPE_KICK",
	}
	PushType_value = map[string]int32{
		"PUSH_TYPE_UNSPECIFIED":  0,
		"PUSH_TYPE_NOTIFY":       1,
		"PUSH_TYPE_ANNOUNCEMENT": 2,
		"PUSH_TYPE_CHAT":         3,
		"PUSH_TYPE_KICK":         4,
	}
)

func (x PushType) Enum() *PushType {
	p := new(PushType)
	*p = x
	return p
}

func (x PushType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushType) Descriptor() protoreflect.EnumDescriptor {
	return file_enums_enums_proto_enumTypes[0].Descriptor()
}

func (PushType) Type() protoreflect.EnumType {
	return &file_enums_enums_proto_enumTypes[0]
}

func (x PushType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushType.Descriptor instead.
func (PushType) EnumDescriptor() ([]byte, []int) {
	return file_enums_enums_proto_rawDescGZIP(), []int{0}
}

type CompressionType int32

const (
	CompressionType_COMPRESSION_TYPE_NONE CompressionType = 0
	CompressionType_COMPRESSION_TYPE_GZIP CompressionType = 1
	CompressionType_COMPRESSION_TYPE_ZSTD CompressionType = 2
	CompressionType_COMPRESSION_TYPE_LZ4  CompressionType = 3
)

// Enum value maps for CompressionType.
var (
	CompressionType_name = map[int32]string{
		0: "COMPRESSION_TYPE_NONE",
		1: "COMPRESSION_TYPE_GZIP",
		2: "COMPRESSION_TYPE_ZSTD",
		3: "COMPRESSION_TYPE_LZ4",
	}
	CompressionType_value = map[string]int32{
		"COMPRESSION_TYPE_NONE": 0,
		"COMPRESSION_TYPE_GZIP": 1,
		"COMPRESSION_TYPE_ZSTD": 2,
		"COMPRESSION_TYPE_LZ4":  3,
	}
)

func (x CompressionType) Enum() *CompressionType {
	p := new(CompressionType)
	*p = x
	return p
}

func (x CompressionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompressionType) Descriptor() protoreflect.EnumDescriptor {
	return file_enums_enums_proto_enumTypes[1].Descriptor()
}

func (CompressionType) Type() protoreflect.EnumType {
	return &file_enums_enums_proto_enumTypes[1]
}

func (x CompressionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompressionType.Descriptor instead.
func (CompressionType) EnumDescriptor() ([]byte, []int) {
	return file_enums_enums_proto_rawDescGZIP(), []int{1}
}

var File_enums_enums_proto protoreflect.FileDescriptor

var file_enums_enums_proto_rawDesc = []byte{
	0x0a, 0x11, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2a, 0x7f, 0x0a, 0x08, 0x50, 0x75,
	0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e,
	0x4f, 0x54, 0x49, 0x46, 0x59, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x50, 0x55, 0x53, 0x48, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x4e, 0x4e, 0x4f, 0x55, 0x4e, 0x43, 0x45, 0x4d, 0x45, 0x4e,
	0x54, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x43, 0x48, 0x41, 0x54, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x55, 0x53, 0x48, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x4b, 0x49, 0x43, 0x4b, 0x10, 0x04, 0x2a, 0x7c, 0x0a, 0x0f, 0x43,
	0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19,
	0x0a, 0x15, 0x43, 0x4f, 0x4d, 0x50, 0x52, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4f, 0x4d,
	0x50, 0x52, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x5a,
	0x49, 0x50, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4f, 0x4d, 0x50, 0x52, 0x45, 0x53, 0x53,
	0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x5a, 0x53, 0x54, 0x44, 0x10, 0x02, 0x12,
	0x18, 0x0a, 0x14, 0x43, 0x4f, 0x4d, 0x50, 0x52, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x4c, 0x5a, 0x34, 0x10, 0x03, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x65,
	0x6e, 0x75, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enums_enums_proto_rawDescOnce sync.Once
	file_enums_enums_proto_rawDescData = file_enums_enums_proto_rawDesc
)

func file_enums_enums_proto_rawDescGZIP() []byte {
	file_enums_enums_proto_rawDescOnce.Do(func() {
		file_enums_enums_proto_rawDescData = protoimpl.X.CompressGZIP(file_enums_enums_proto_rawDescData)
	})
	return file_enums_enums_proto_rawDescData
}

var file_enums_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_enums_enums_proto_goTypes = []interface{}{
	(PushType)(0),        // 0: enums.PushType
	(CompressionType)(0), // 1: enums.CompressionType
}
var file_enums_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enums_enums_proto_init() }
func file_enums_enums_proto_init() {
	if File_enums_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enums_enums_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enums_enums_proto_goTypes,
		DependencyIndexes: file_enums_enums_proto_depIdxs,
		EnumInfos:         file_enums_enums_proto_enumTypes,
	}.Build()
	File_enums_enums_proto = out.File
	file_enums_enums_proto_rawDesc = nil
	file_enums_enums_proto_goTypes = nil
	file_enums_enums_proto_depIdxs = nil
}
