// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.2
// source: gateway/gateway.proto

package gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GatewayStream_OnData_FullMethodName = "/gateway.GatewayStream/onData"
)

// GatewayStreamClient is the client API for GatewayStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayStreamClient interface {
	OnData(ctx context.Context, opts ...grpc.CallOption) (GatewayStream_OnDataClient, error)
}

type gatewayStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayStreamClient(cc grpc.ClientConnInterface) GatewayStreamClient {
	return &gatewayStreamClient{cc}
}

func (c *gatewayStreamClient) OnData(ctx context.Context, opts ...grpc.CallOption) (GatewayStream_OnDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &GatewayStream_ServiceDesc.Streams[0], GatewayStream_OnData_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &gatewayStreamOnDataClient{stream}
	return x, nil
}

type GatewayStream_OnDataClient interface {
	Send(*StreamData) error
	Recv() (*StreamData, error)
	grpc.ClientStream
}

type gatewayStreamOnDataClient struct {
	grpc.ClientStream
}

func (x *gatewayStreamOnDataClient) Send(m *StreamData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gatewayStreamOnDataClient) Recv() (*StreamData, error) {
	m := new(StreamData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GatewayStreamServer is the server API for GatewayStream service.
// All implementations must embed UnimplementedGatewayStreamServer
// for forward compatibility
type GatewayStreamServer interface {
	OnData(GatewayStream_OnDataServer) error
	mustEmbedUnimplementedGatewayStreamServer()
}

// UnimplementedGatewayStreamServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayStreamServer struct {
}

func (UnimplementedGatewayStreamServer) OnData(GatewayStream_OnDataServer) error {
	return status.Errorf(codes.Unimplemented, "method OnData not implemented")
}
func (UnimplementedGatewayStreamServer) mustEmbedUnimplementedGatewayStreamServer() {}

// UnsafeGatewayStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayStreamServer will
// result in compilation errors.
type UnsafeGatewayStreamServer interface {
	mustEmbedUnimplementedGatewayStreamServer()
}

func RegisterGatewayStreamServer(s grpc.ServiceRegistrar, srv GatewayStreamServer) {
	s.RegisterService(&GatewayStream_ServiceDesc, srv)
}

func _GatewayStream_OnData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayStreamServer).OnData(&gatewayStreamOnDataServer{stream})
}

type GatewayStream_OnDataServer interface {
	Send(*StreamData) error
	Recv() (*StreamData, error)
	grpc.ServerStream
}

type gatewayStreamOnDataServer struct {
	grpc.ServerStream
}

func (x *gatewayStreamOnDataServer) Send(m *StreamData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gatewayStreamOnDataServer) Recv() (*StreamData, error) {
	m := new(StreamData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GatewayStream_ServiceDesc is the grpc.ServiceDesc for GatewayStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.GatewayStream",
	HandlerType: (*GatewayStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "onData",
			Handler:       _GatewayStream_OnData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gateway/gateway.proto",
}
