// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.2
// source: sgate/gateway.proto

package sgate

import (
	commonstruct "github.com/streasure/protocol/commonstruct"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GatewayService_StreamMessages_FullMethodName = "/sgate.GatewayService/StreamMessages"
	GatewayService_SendMessage_FullMethodName    = "/sgate.GatewayService/SendMessage"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	StreamMessages(ctx context.Context, opts ...grpc.CallOption) (GatewayService_StreamMessagesClient, error)
	SendMessage(ctx context.Context, in *commonstruct.Message, opts ...grpc.CallOption) (*commonstruct.Message, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) StreamMessages(ctx context.Context, opts ...grpc.CallOption) (GatewayService_StreamMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[0], GatewayService_StreamMessages_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &gatewayServiceStreamMessagesClient{stream}
	return x, nil
}

type GatewayService_StreamMessagesClient interface {
	Send(*commonstruct.Message) error
	Recv() (*commonstruct.Message, error)
	grpc.ClientStream
}

type gatewayServiceStreamMessagesClient struct {
	grpc.ClientStream
}

func (x *gatewayServiceStreamMessagesClient) Send(m *commonstruct.Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gatewayServiceStreamMessagesClient) Recv() (*commonstruct.Message, error) {
	m := new(commonstruct.Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gatewayServiceClient) SendMessage(ctx context.Context, in *commonstruct.Message, opts ...grpc.CallOption) (*commonstruct.Message, error) {
	out := new(commonstruct.Message)
	err := c.cc.Invoke(ctx, GatewayService_SendMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility
type GatewayServiceServer interface {
	StreamMessages(GatewayService_StreamMessagesServer) error
	SendMessage(context.Context, *commonstruct.Message) (*commonstruct.Message, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayServiceServer struct {
}

func (UnimplementedGatewayServiceServer) StreamMessages(GatewayService_StreamMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMessages not implemented")
}
func (UnimplementedGatewayServiceServer) SendMessage(context.Context, *commonstruct.Message) (*commonstruct.Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_StreamMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayServiceServer).StreamMessages(&gatewayServiceStreamMessagesServer{stream})
}

type GatewayService_StreamMessagesServer interface {
	Send(*commonstruct.Message) error
	Recv() (*commonstruct.Message, error)
	grpc.ServerStream
}

type gatewayServiceStreamMessagesServer struct {
	grpc.ServerStream
}

func (x *gatewayServiceStreamMessagesServer) Send(m *commonstruct.Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gatewayServiceStreamMessagesServer) Recv() (*commonstruct.Message, error) {
	m := new(commonstruct.Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GatewayService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonstruct.Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SendMessage(ctx, req.(*commonstruct.Message))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgate.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _GatewayService_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessages",
			Handler:       _GatewayService_StreamMessages_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sgate/gateway.proto",
}
